[project]
name = "cllama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.26",
    "langchain-ollama>=0.3.3",
    "python-dotenv>=1.1.0",
    "streamlit>=1.46.0",
]
