name: Cllama Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency_review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Dependency Review Action
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always

  lint:
    name: Lint Code with Black and Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install lint tools
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      - name: Run Black (check only)
        run: black --check .

      - name: Run Ruff lint checks
        run: ruff check .

  run_pytest:
    name: Run Pytest Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv package manager
        run: pip install uv

      - name: Sync dependencies with uv
        run: uv sync

      - name: Run tests with pytest
        env:
          PYTHONPATH: src
        run: uv run pytest -v --maxfail=3 --disable-warnings --tb=short
